version: "3"

services:
  server-test:
    env_file: .env
    container_name: ${server-simple-http}
    image: ${server-simple-http}
    volumes:
      - ./src:/var/www
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"

