version: "3"

services:
  server-test:
    restart: always
    env_file: .env
    container_name: ${cnt-server-simple-http}
    image: ${img-server-simple-http}
    volumes:
      - ./src:/var/www
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"

